import React, { useState } from 'react';
import html2canvas from 'html2canvas';
import ColorPalette from './ColorPalette';

const AnalysisResult = ({ data, imagePreview, onTryAgain }) => {
  const [overlayColor, setOverlayColor] = useState('');

  const handleSaveAsPNG = () => {
    const captureArea = document.getElementById('capture-area');
    if (captureArea) {
      html2canvas(captureArea, {
        backgroundColor: document.body.classList.contains('dark') ? '#111827' : '#F9F9F9',
        useCORS: true,
      }).then(canvas => {
        const image = canvas.toDataURL('image/png');
        const link = document.createElement('a');
        link.href = image;
        link.download = 'my-color-analysis.png';
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
      });
    }
  };

  return (
    <>
      <div id="capture-area">
        <div className="result-wrapper modern-result-wrapper">
          <h1 className="result-title">Your Personal Color Analysis</h1>
          {data.colorAnalysis && (
            <div className="result-header">
              <div className="image-preview-wrapper">
                <img src={imagePreview} alt="User" className="image-preview" />
                {overlayColor && (
                  <div className="color-overlay" style={{ backgroundColor: overlayColor }}></div>
                )}
              </div>
            </div>
          )}
          {data.colorAnalysis && (
            <div className="analysis-summary analysis-summary-below">
              <span className="season-tag">{data.colorAnalysis.season}</span>
              <p>{data.colorAnalysis.description}</p>
            </div>
          )}

          {/* Modern tip card, translated to English */}
          <div className="tip-box card modern-tip-box">
            <span role="img" aria-label="tip" className="tip-icon">💡</span>
            <span className="tip-text"><b>Tip:</b> Hover over a color to see its details, and click to preview it on your photo!</span>
          </div>

          <ColorPalette
            title="Your Best Colors"
            description={data.recommendedColors.description}
            palette={data.recommendedColors.palette}
            onColorClick={setOverlayColor}
          />

          <ColorPalette
            title="Colors to Avoid"
            description={data.avoidColors.description}
            palette={data.avoidColors.palette}
            onColorClick={setOverlayColor}
          />

          {/* Modern disclaimer card, translated to English */}
          <div className="disclaimer-box card modern-disclaimer-box">
            <p><strong>Disclaimer:</strong> This color analysis is generated by AI. While based on color theory principles, results may not be as accurate as a direct professional analysis. Factors such as image quality, lighting, and screen settings can affect online assessment. For the most precise results, consider consulting a professional color analyst.</p>
          </div>
        </div>
      </div>

      <div className="action-buttons-container">
        <button onClick={onTryAgain} className="action-button try-again">Try Again</button>
        <button onClick={handleSaveAsPNG} className="action-button save-png">Save as PNG</button>
      </div>
    </>
  );
};
export default AnalysisResult;
